force-app/main/default/objects/Chat_Notifications__c/Chat_Notifications__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the settings for the LiveAgent chat notifications.</description>
    <label>Chat Notifications</label>
</CustomObject>

force-app/main/default/objects/Chat_Notifications__c/fields/Chat_Message_Notification_Active__c.field-meta.xml
<CustomField>
    <fullName>Chat_Message_Notification_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chat Message Notification Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chat_Notifications__c/fields/Chat_Message_Sound_Active__c.field-meta.xml
<CustomField>
    <fullName>Chat_Message_Sound_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chat Message Sound Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chat_Notifications__c/fields/Chat_Request_Active__c.field-meta.xml
<CustomField>
    <fullName>Chat_Request_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chat Request Notification Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chat_Notifications__c/fields/Chat_Request_Sound_Active__c.field-meta.xml
<CustomField>
    <fullName>Chat_Request_Sound_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chat Request Sound Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotificationsSetup.cls
/**
 * Created by gruiz on 2019-09-25.
 */

public with sharing class NotificationsSetup {

	@AuraEnabled(Cacheable=true)
	public static ChatOptions getChatNotifications() {
		Chat_Notifications__c chatNotifications = Chat_Notifications__c.getInstance();
		if (chatNotifications.Id != null) {
			return new ChatOptions(chatNotifications.Chat_Request_Active__c,
					chatNotifications.Chat_Message_Notification_Active__c, chatNotifications.Chat_Request_Sound_Active__c,
					chatNotifications.Chat_Message_Sound_Active__c, chatNotifications.Chat_Request_Message__c);
		} else {
			return new ChatOptions();
		}
	}

	@AuraEnabled
	public static void updateChatNotifications(String chatOptionsJSON) {
		ChatOptions chatOptions = (ChatOptions) JSON.deserialize(chatOptionsJSON, ChatOptions.class);
		Chat_Notifications__c chatNotifications = Chat_Notifications__c.getInstance();
		chatNotifications.Chat_Request_Active__c = chatOptions.chatActive;
		chatNotifications.Chat_Message_Notification_Active__c = chatOptions.messageActive;
		chatNotifications.Chat_Request_Sound_Active__c = chatOptions.chatSoundActive;
		chatNotifications.Chat_Message_Sound_Active__c = chatOptions.messageSoundActive;
		chatNotifications.Chat_Request_Message__c = chatOptions.chatMessage;
		upsert chatNotifications;
	}

	public class ChatOptions {
		@AuraEnabled Boolean chatActive { get; set; }
		@AuraEnabled Boolean messageActive { get; set; }
		@AuraEnabled Boolean chatSoundActive { get; set; }
		@AuraEnabled Boolean messageSoundActive { get; set; }
		@AuraEnabled String chatMessage { get; set; }

		public ChatOptions() {
			this.chatActive = false;
			this.messageActive = false;
			this.chatSoundActive = false;
			this.messageSoundActive = false;
			this.chatMessage = 'You have a new conversation request';
		}

		public ChatOptions(Boolean chatActive, Boolean messageActive, Boolean chatSoundActive,
				Boolean messageSoundActive, String chatMessage) {
			this.chatActive = chatActive;
			this.messageActive = messageActive;
			this.chatSoundActive = chatSoundActive;
			this.messageSoundActive = messageSoundActive;
			this.chatMessage = chatMessage;
		}
	}

}